default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-xml
    -   id: check-toml
    -   id: check-json
    -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
